config/routes.rb
LearnCucumber::Application.routes.draw do

  match 'signup', :controller => 'users', :action => 'new'
  match 'logout', :controller => 'sessions', :action => 'destroy'
  match 'login', :controller => 'sessions', :action => 'new'

  resources :users
  resources :sessions

  resources :articles, only: [:index, :new, :create]
  resources :products, only: [:show, :index]

  root :to => 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :admin, :email, :username, :password, :password_confirmation

  attr_accessor :password
  before_create :prepare_password

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.matching_password?(pass)
  end

  def matching_password?(pass)
    self.password_hash == encrypt_password(pass)
  end

  private

  def prepare_password
    self.password_salt = Digest::SHA1.hexdigest([Time.now, rand].join)
    self.password_hash = encrypt_password(password)
  end

  def encrypt_password(pass)
    Digest::SHA1.hexdigest([pass, password_salt].join)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication

  # helper :all # include all helpers, all the time
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create!(params[:article])
    flash[:notice] = "New article created."
    redirect_to articles_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find(params[:id])
  end

  def index
    @products = Product.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:login], params[:password])
    if user
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully."
      redirect_to user
    else
      flash.now[:error] = "Invalid login or password."
      render :action => 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been logged out."
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Thank you for signing up! You are now logged in."
      redirect_to @user
    else
      render :action => 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
  def title(page_title, show_title = true)
    @content_for_title = page_title.to_s
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args.map(&:to_s)) }
  end

  def javascript(*args)
    args = args.map { |arg| arg == :defaults ? arg : arg.to_s }
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/index.html.erb
<%= flash[:notice] %>

<h1>Articles</h1>
<% @articles.each do |article| %>
  <h2><%= h(article.title) %></h2>
  <p><%= h(article.content) %></p>
<% end %>

<p><%= link_to "New Article", new_article_path %></p>

app/views/articles/new.html.erb
<%= form_for @article do |f| %>
  <ul>
    <li>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </li>
    <li>
      <%= f.label :content %>
      <%= f.text_field :content %>
    </li>
    <li>
      <%= f.submit "Create" %>
    </li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!-- <!DOCTYPE html>
<html>
<head>
  <title>LearnCucumber</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html> -->
<!DOCTYPE html>
<html>
  <head>
    <title><%= h(yield(:title) || "Untitled") %></title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <p id="loginbar">
      <% if logged_in? %>
        Currently logged in as <%=h current_user.username %>! Not you?
        <%= link_to "Log out", logout_path %>
      <% else %>
        <%= link_to "Sign up", signup_path %> or
        <%= link_to "log in", login_path %>.
      <% end %>
      </p>

      <%- flash.each do |name, msg| -%>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <%- end -%>

      <%- if show_title? -%>
        <h1><%=h yield(:title) %></h1>
      <%- end -%>

      <%= yield %>
    </div>
  </body>
</html>

app/views/products/index.html.erb
<table id="products">
<% for product in @products %>
  <tr>
    <td><%= h product.name %></td>
    <td><%= number_to_currency product.price %></td>
  </tr>
<% end %>
</table>

app/views/products/show.html.erb
<h1><%= h(@product.name) %></h1>
<p><%= number_to_currency(@product.price, :unit => "&pound;") %></p>

app/views/users/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= form_for @user do |f| %>
  <%= @user.errors %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit "Sign up" %></p>
<% end %>

app/views/users/show.html.erb
<% title "Profile for " + @user.username %>

<p>This user currently has no bio.</p>

<p>Email: <%=h @user.email %></p>

<% if current_user && current_user.admin? || current_user == @user %>
  <p><%= link_to "Edit Profile", edit_user_path(@user) %></p>
<% end %>